### ISSUE TITLE
ReferenceError: window is not defined,when I build for vuepress

### ISSUE THREAD

**Issue by buqiyuan** [alvarotrigo/vue-fullpage.js#126]
### Description
```
ReferenceError: window is not defined
    at Object.<anonymous> (node_modules/vue-fullpage.js/dist/vue-fullpage.common.js:94:166)
    at __webpack_require__ (node_modules/vue-fullpage.js/dist/vue-fullpage.common.js:33:0)
    at Object.<anonymous> (node_modules/vue-fullpage.js/dist/vue-fullpage.common.js:132:0)
    at __webpack_require__ (node_modules/vue-fullpage.js/dist/vue-fullpage.common.js:33:0)
    at Object.<anonymous> (node_modules/vue-fullpage.js/dist/vue-fullpage.common.js:102:0)
```
### Link to isolated reproduction with no external CSS / JS
[Ideally in codepen.io or codesandbox.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operating system, device, ...]

**Comment by alvarotrigo** [comment]
Can you provide us a way to reproduce the issue?
What code are you using?

**Comment by buqiyuan** [comment]
use in my enhanceApp.js(Vuepress):
```
import VueFullPage from 'vue-fullpage.js'
import VueECharts from 'vue-echarts' //注册图表
import 'animate.css'//引入css动画库

export default ({

                  Vue, // VuePress 正在使用的 Vue 构造函数
                  options, // 附加到根实例的一些选项
                  router, // 当前应用的路由实例
                  siteData // 站点元数据

                }) => {
  Vue.use(VueFullPage)
  // ...做一些其他的应用级别的优化
  Vue.component('v-chart', VueECharts)
}
```
but now I resolve this error,now I use code like this:
```
import VueECharts from 'vue-echarts' //注册图表
import 'animate.css'//引入css动画库

export default ({

                  Vue, // VuePress 正在使用的 Vue 构造函数
                  options, // 附加到根实例的一些选项
                  router, // 当前应用的路由实例
                  siteData // 站点元数据

                }) => {

  // ...做一些其他的应用级别的优化
  import('vue-fullpage.js').then(module => {
    Vue.use(module.default)
  })
  Vue.component('v-chart', VueECharts)
}
```

**Comment by alvarotrigo** [comment]
Glad you managed to solve it! ;)

**Comment by lecer** [comment]
@buqiyuan 联系不到你，看了下你的博客，所以就留言在这儿了。
请问你用的vuepress和fullpage.js版本是多少。在引用的full-page组件的页是写在md文件中了吗？我这边，试了好多版本，最新到1.0版的vuepress/fullpage都还是在构建的时候报window is not defined.
想知道你那边的配置，或方便的话，给个demo。我看你博客的关于我部分有应用。
