### ISSUE TITLE
Why am I running an error on Vite

### ISSUE THREAD

**Issue by qaz74423** [alvarotrigo/vue-fullpage.js#251]
[ERROR] [plugin vite:dep-scan] Missing "./dist/vue-fullpage.es" export in "vue-fullpage.js" package

    node_modules/.pnpm/registry.npmmirror.com+vite@2.9.9/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:39923:7:
      39923 │   throw new Error(
            ╵         ^

    at bail (E:\study\landing-page\fullpage-app\node_modules\.pnpm\registry.npmmirror.com+vite@2.9.9\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:39923:8)
    at resolve (E:\study\landing-page\fullpage-app\node_modules\.pnpm\registry.npmmirror.com+vite@2.9.9\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:40000:10)
    at resolveExports (E:\study\landing-page\fullpage-app\node_modules\.pnpm\registry.npmmirror.com+vite@2.9.9\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:40674:12)
    at resolveDeepImport (E:\study\landing-page\fullpage-app\node_modules\.pnpm\registry.npmmirror.com+vite@2.9.9\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:40692:31)
    at tryNodeResolve (E:\study\landing-page\fullpage-app\node_modules\.pnpm\registry.npmmirror.com+vite@2.9.9\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:40465:20)
    at Context.resolveId (E:\study\landing-page\fullpage-app\node_modules\.pnpm\registry.npmmirror.com+vite@2.9.9\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:40273:28)
    at Object.resolveId (E:\study\landing-page\fullpage-app\node_modules\.pnpm\registry.npmmirror.com+vite@2.9.9\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:38837:55)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolve (E:\study\landing-page\fullpage-app\node_modules\.pnpm\registry.npmmirror.com+vite@2.9.9\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:39049:26)
    at async E:\study\landing-page\fullpage-app\node_modules\.pnpm\registry.npmmirror.com+vite@2.9.9\node_modules\vite\dist\node\chunkssbuild\lib\main.js:1137:7)
    at E:\study\landing-page\fullpage-app\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.14.39\node_modules\esbuild\lib\main.js:2079:17
    at new Promise (<anonymous>)
    at Object.build (E:\study\landing-page\fullpage-app\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.14.39\node_modules\esbuild\lib\main.js:2078:14)
    at Object.build (E:\study\landing-page\fullpage-app\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.14.39\node_modules\esbuild\lib\main.js:1927:51)
    at E:\study\landing-page\fullpage-app\node_modules\.pnpm\registry.npmmirror.com+vite@2.9.9\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:38997:54
    at Array.map (<anonymous>)

  The plugin "vite:dep-scan" was triggered by this import

    src/main.ts:5:24:      5 │ import VueFullPage from 'vue-fullpage.js/dist/vue-fullpage.es'
        ╵                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Build failed with 1 error:
node_modules/.pnpm/registry.npmmirror.com+vite@2.9.9/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:39923:7: ERROR: [plugin: vite:dep-scan] Missing "./dist/vue-fullpage.es" export in "vue-fullpage.js" package

**Comment by alvarotrigo** [comment]
What version are you using of vue-fullpage?

**Comment by qaz74423** [comment]
> What version are you using of vue-fullpage?

is latest

**Comment by JonathanSchndr** [comment]
@qaz74423 can you please recreate the error in an example so we can verify this. I think the error is local to you. For example, we are not using Vite 2.9.9 which appears in your logs.

**Comment by alvarotrigo** [comment]
@qaz74423 can you provide an isolated reproduction in https://codesandbox.io/  so we can investigate the issue?

**Comment by qaz74423** [comment]
> @qaz74423 can you provide an isolated reproduction in https://codesandbox.io/ so we can investigate the issue?
i will try,but my network may not be able to provide it

**Comment by JonathanSchndr** [comment]
please swap once 
`import VueFullPage from 'vue-fullpage.js/dist/vue-fullpage.es'`
to 
`import VueFullPage from 'vue-fullpage.js'`

.. and try again.

**Comment by qaz74423** [comment]
> please swap once `import VueFullPage from 'vue-fullpage.js/dist/vue-fullpage.es'` to `import VueFullPage from 'vue-fullpage.js'`
> 
> .. and try again.

Yeah, that's the problem，nice，bro.

**Comment by JonathanSchndr** [comment]
perfect, sorry for the outaded readme, i will create an update for this.
